--------------------------------------------------------
--  已建立檔案 - 星期三-十一月-11-2020   
--------------------------------------------------------
REM INSERTING into SAJET.SYS_BASE_PARAM
SET DEFINE OFF;
Insert into SAJET.SYS_BASE_PARAM (PROGRAM,PARAM_NAME,PARAM_VALUE,PARAM_TYPE,DEFAULT_VALUE,PARAM_DESC) values ('WIP','RC Input','SELECT MACHINE_CODE, D.STATUS_NAME, RUN_FLAG, DEFAULT_STATUS
FROM SAJET.SYS_RC_PROCESS_MACHINE A, SAJET.SYS_MACHINE B, SAJET.G_MACHINE_STATUS C, SAJET.SYS_MACHINE_STATUS D
WHERE A.PROCESS_ID = :PROCESS_ID AND A.MACHINE_ID = B.MACHINE_ID AND A.MACHINE_ID = C.MACHINE_ID
AND C.CURRENT_STATUS_ID = D.STATUS_ID
AND A.ENABLED = ''Y'' AND B.ENABLED = ''Y'' ORDER BY MACHINE_CODE ','SQL','機台','1;-1');
Insert into SAJET.SYS_BASE_PARAM (PROGRAM,PARAM_NAME,PARAM_VALUE,PARAM_TYPE,DEFAULT_VALUE,PARAM_DESC) values ('WIP','RC Output','SELECT MACHINE_CODE, D.STATUS_NAME, RUN_FLAG, DEFAULT_STATUS
FROM SAJET.G_RC_TRAVEL_MACHINE A, SAJET.G_RC_STATUS E, SAJET.SYS_MACHINE B, SAJET.G_MACHINE_STATUS C, SAJET.SYS_MACHINE_STATUS D
WHERE A.TRAVEL_ID = E.TRAVEL_ID AND A.RC_NO = E.RC_NO AND E.RC_NO = :RC_NO AND A.MACHINE_ID = B.MACHINE_ID AND A.MACHINE_ID = C.MACHINE_ID
AND C.CURRENT_STATUS_ID = D.STATUS_ID
AND B.ENABLED = ''Y'' ORDER BY MACHINE_CODE','SQL','機台','1;-1;0');
