CREATE OR REPLACE VIEW V_G_MACHINE_T4_BINDING AS
SELECT   CASE WHEN SUBSTR(r.rc_no_t4,1,3) = '10B' THEN '10A' || SUBSTR(r.rc_no_t4,4) ELSE NULL END "RC_NO_10A"
, r."RC_NO_10C",r."PROCESS_ID_10C",r."NODE_ID_10C",r."RC_NO_T4",r."PROCESS_ID_T4",r."NODE_ID_T4",r."MACHINE_ID",r."BINDING_QTY",r."CHECK_BOM",r."UPDATE_USERID",r."UPDATE_TIME"
FROM  G_MACHINE_T4_BINDING r;
