
  CREATE TABLE "SAJET"."G_MACHINE_T4_BINDING" 
   (	"RC_NO_10C" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROCESS_ID_10C" NUMBER NOT NULL ENABLE, 
	"NODE_ID_10C" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"RC_NO_T4" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROCESS_ID_T4" NUMBER NOT NULL ENABLE, 
	"NODE_ID_T4" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"MACHINE_ID" NUMBER NOT NULL ENABLE, 
	"BINDING_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CHECK_BOM" VARCHAR2(5 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."RC_NO_10C" IS '10C 的流程卡號';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."PROCESS_ID_10C" IS '10C 的流程卡所在製程的 ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."NODE_ID_10C" IS '10C 的流程卡所在生產途程節點 ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."RC_NO_T4" IS '綁定 T4 的流程卡號';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."PROCESS_ID_T4" IS '綁定 T4 的流程卡的製程 ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."NODE_ID_T4" IS '綁定 T4 的流程卡的生產途程節點 ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."MACHINE_ID" IS '機台 ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."BINDING_QTY" IS '綁定數量';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."CHECK_BOM" IS '是否檢查 BOM';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."UPDATE_USERID" IS '更新人員 ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_T4_BINDING"."UPDATE_TIME" IS '更新時間';
 
