
  CREATE TABLE "SAJET"."G_PLC_CUTTING_WEIGHT" 
   (	"DATARECORD_ID" NUMBER, 
	"WORK_ORDER" VARCHAR2(50 BYTE), 
	"LINE" NUMBER, 
	"STATUS_FLAG" VARCHAR2(5 BYTE), 
	"WEIGHT" NUMBER, 
	"DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."G_PLC_CUTTING_WEIGHT"."DATARECORD_ID" IS '資料 ID';
 
   COMMENT ON COLUMN "SAJET"."G_PLC_CUTTING_WEIGHT"."WORK_ORDER" IS '工單號碼';
 
   COMMENT ON COLUMN "SAJET"."G_PLC_CUTTING_WEIGHT"."LINE" IS '12000/8000 (12000: 送往 12000T / 8000: 送往 8000T)';
 
   COMMENT ON COLUMN "SAJET"."G_PLC_CUTTING_WEIGHT"."STATUS_FLAG" IS 'I/G/N (I:進站, G:出站良品, N:出站不良品)';
 
   COMMENT ON COLUMN "SAJET"."G_PLC_CUTTING_WEIGHT"."WEIGHT" IS '重量';
 
   COMMENT ON COLUMN "SAJET"."G_PLC_CUTTING_WEIGHT"."DATETIME" IS '記錄時間';
 
