
  CREATE TABLE "SAJET"."SYS_PART_QC_PLAN" 
   (	"PART_ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"SAMPLING_ID" NUMBER NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_PLAN"."PART_ID" IS 'SYS_PART.PART_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_PLAN"."PROCESS_ID" IS 'SYS_PROCESS.PROCESS_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_PLAN"."SAMPLING_ID" IS 'SYS_QC_SAMPLING_PLAN.SAMPLING_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_PLAN"."UPDATE_USERID" IS '更新資料人員的 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_PLAN"."UPDATE_TIME" IS '更新時間';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_PLAN"."ENABLED" IS '資料啟用狀態';
 
