
  CREATE TABLE "SAJET"."SYS_END_PROCESS" 
   (	"PART_ID" NUMBER NOT NULL ENABLE, 
	"ROUTE_ID" NUMBER NOT NULL ENABLE, 
	"NODE_ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ENABLED" VARCHAR2(5 BYTE) DEFAULT 'Y' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."PART_ID" IS 'SAJET.SYS_PART.PART_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."ROUTE_ID" IS 'SAJET.SYS_RC_ROUTE.ROUTE_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."NODE_ID" IS 'SAJET.SYS_RC_ROUTE_DETAIL.NODE_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."PROCESS_ID" IS 'SAJET.SYS_PROCESS.PROCESS_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."UPDATE_USERID" IS '更新員工 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."UPDATE_TIME" IS '更新時間';
 
   COMMENT ON COLUMN "SAJET"."SYS_END_PROCESS"."ENABLED" IS '資料啟用狀態（Y：啟用/ N：停用/ D：刪除）';
 
