
  CREATE TABLE "SAJET"."G_RC_QC_LOG" 
   (	"RC_NO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PART_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"NODE_ID" NUMBER NOT NULL ENABLE, 
	"QC_EMP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."G_RC_QC_LOG"."RC_NO" IS '流程卡號';
 
   COMMENT ON COLUMN "SAJET"."G_RC_QC_LOG"."PART_ID" IS '料號 ID';
 
   COMMENT ON COLUMN "SAJET"."G_RC_QC_LOG"."PROCESS_ID" IS '製程 ID';
 
   COMMENT ON COLUMN "SAJET"."G_RC_QC_LOG"."NODE_ID" IS '生產途程節點 ID';
 
   COMMENT ON COLUMN "SAJET"."G_RC_QC_LOG"."QC_EMP_ID" IS '檢驗人員 ID';
 
   COMMENT ON COLUMN "SAJET"."G_RC_QC_LOG"."UPDATE_TIME" IS '資料更新時間';
 
