--------------------------------------------------------
--  已建立檔案 - 星期一-三月-15-2021   
--------------------------------------------------------
REM INSERTING into SAJET.SYS_BASE_PARAM
SET DEFINE OFF;
Insert into SAJET.SYS_BASE_PARAM (PROGRAM,PARAM_NAME,PARAM_VALUE,PARAM_TYPE,DEFAULT_VALUE,PARAM_DESC) values ('WIP','IPQC','SELECT 
A.RC_NO, A.WORK_ORDER, B.PART_NO, ROUTE_NAME, PROCESS_NAME, FACTORY_CODE, A.VERSION, A.PROCESS_ID, 
A.PART_ID, CURRENT_QTY QTY, CURRENT_QTY GOOD_QTY, 0 SCRAP_QTY , F.WO_OPTION2, B.SPEC1, B.SPEC2
FROM
SAJET.G_RC_STATUS A, SAJET.SYS_PART B, SAJET.SYS_RC_ROUTE C, SAJET.SYS_PROCESS D, SAJET.SYS_FACTORY E, SAJET.G_WO_BASE F
WHERE A.PART_ID = B.PART_ID AND A.ROUTE_ID = C.ROUTE_ID
AND A.PROCESS_ID = D.PROCESS_ID AND A.FACTORY_ID = E.FACTORY_ID
AND A.RC_NO = :SN
AND A.WORK_ORDER = F.WORK_ORDER ','SQL','SQL',null);
