
  CREATE TABLE "SAJET"."G_MACHINE_DOWN_EXCLUDE" 
   (	"RC_NO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NODE_ID" NUMBER NOT NULL ENABLE, 
	"TRAVEL_ID" NUMBER NOT NULL ENABLE, 
	"MACHINE_ID" NUMBER, 
	"START_TIME" DATE NOT NULL ENABLE, 
	"END_TIME" DATE, 
	"REASON_ID" NUMBER, 
	"LOAD_QTY" NUMBER DEFAULT 0, 
	"DATE_CODE" VARCHAR2(20 BYTE), 
	"STOVE_SEQ" VARCHAR2(20 BYTE), 
	"WORK_TIME_MINUTE" NUMBER DEFAULT 0, 
	"WORK_TIME_SECOND" FLOAT(126) DEFAULT 0, 
	"COUNT_WORKTIME" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"REMARK" VARCHAR2(500 BYTE), 
	"REPORT_TYPE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DATA_STATUS" NUMBER, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."RC_NO" IS '流程卡號';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."NODE_ID" IS '途程節點ID';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."TRAVEL_ID" IS '歷程編號';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."MACHINE_ID" IS '機台';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."START_TIME" IS '運轉開始時間';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."END_TIME" IS '運轉結束時間';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."REASON_ID" IS '停機代碼(ID)';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."LOAD_QTY" IS '負載量';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."WORK_TIME_MINUTE" IS '花費時間（分鐘）';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."WORK_TIME_SECOND" IS '花費時間（秒鐘）';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."REMARK" IS '備註';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."UPDATE_USERID" IS '資料異動人員';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."UPDATE_TIME" IS '最後更新時間';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."DATA_STATUS" IS '資料的狀態（0：正常報工收集的資料/ 1：製程跳過執行的資料(途程報工)/ 2：報工完才補的資料）';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."REPORT_TYPE" IS '報工類型（0：無分類/ 1：單張流程卡報工/ 2：整批流程卡報工）';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."COUNT_WORKTIME" IS '是否計算工時（0：要計算工時/ 1：不計算工時）';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."DATE_CODE" IS '若為使用 T4 爐/ T6 爐 的製程，需要記錄使用爐的日期編號';
 
   COMMENT ON COLUMN "SAJET"."G_MACHINE_DOWN_EXCLUDE"."STOVE_SEQ" IS '使用到的 T4 / T6 爐的順序號碼';
 
