
  CREATE TABLE "SAJET"."G_RC_TRAVEL_REWORK" 
   (	"RC_NO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER, 
	"NODE_ID" NUMBER, 
	"REWORK_QTY" NUMBER DEFAULT 0, 
	"UPDATE_TIME" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"TRAVEL_ID" NUMBER NOT NULL ENABLE, 
	"BONUS" NUMBER DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."RC_NO" IS 'G_RC_TRAVEL.RC_NO';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."NODE_ID" IS 'SYS_RC_ROUTE_DETAIL.NODE_ID';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."REWORK_QTY" IS '重工數量';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."UPDATE_TIME" IS '最後更新時間';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."UPDATE_USERID" IS '最後異動人員';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."TRAVEL_ID" IS '歷程編號';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."BONUS" IS '維修站修復數量';
 
   COMMENT ON COLUMN "SAJET"."G_RC_TRAVEL_REWORK"."PROCESS_ID" IS 'SYS_PROCESS.PROCESS_ID';
 

  CREATE INDEX "SAJET"."G_RC_TRAVEL_RE_RN_IDX" ON "SAJET"."G_RC_TRAVEL_REWORK" ("RC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSSNIDX" ;
 

  CREATE INDEX "SAJET"."G_RC_TRAVEL_RE_UT_IDX" ON "SAJET"."G_RC_TRAVEL_REWORK" ("UPDATE_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSSNIDX" ;
 
