
  CREATE TABLE "SAJET"."G_RC_TRAVEL_PARAM_VALUE" 
   (	"RC_NO" VARCHAR2(50 BYTE), 
	"SERIAL_NUMBER" VARCHAR2(40 BYTE), 
	"TRAVEL_ID" NUMBER, 
	"ITEM_PHASE" VARCHAR2(1 BYTE), 
	"ITEM_TYPE" NUMBER, 
	"ITEM_ID" NUMBER, 
	"ITEM_NAME" VARCHAR2(30 BYTE), 
	"ITEM_VALUE" VARCHAR2(300 BYTE), 
	"VALUE_TYPE" VARCHAR2(1 BYTE), 
	"UPDATE_USERID" NUMBER, 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSRT" ;
 

  CREATE INDEX "SAJET"."G_RC_TRAVEL_PARAM_TEST_ID" ON "SAJET"."G_RC_TRAVEL_PARAM_VALUE" ("TRAVEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSRTIDX" ;
 
