
  CREATE TABLE "SAJET"."SYS_PROCESS_OPTION" 
   (	"FACTORY_ID" NUMBER NOT NULL ENABLE, 
	"STAGE_ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"OPTION1" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION2" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION3" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION4" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION5" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION6" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION7" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION8" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION9" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION10" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "SYS_PROCESS_OPTION_PK" PRIMARY KEY ("PROCESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."FACTORY_ID" IS 'SYS_FACTORY.FACTORY_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."STAGE_ID" IS 'SYS_STAGE.STAGE_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."PROCESS_ID" IS 'SYS_PROCESS.PROCESS_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."OPTION1" IS '是否列印防水標籤';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."OPTION2" IS '使用 T4 爐';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."OPTION3" IS '使用 T6 爐';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."OPTION4" IS '10C 起始投入站';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."OPTION5" IS '10C 入庫站';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."UPDATE_USERID" IS '更新人員';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."UPDATE_TIME" IS '更新時間';
 
