
  CREATE TABLE "SAJET"."SYS_HT_PART_QC_PLAN" 
   (	"SPQP_ID" NUMBER, 
	"PART_ID" NUMBER, 
	"VERSION" VARCHAR2(30 BYTE), 
	"ROUTE_ID" NUMBER, 
	"NODE_ID" NUMBER, 
	"SAMPLING_ID" NUMBER, 
	"UPDATE_USERID" NUMBER, 
	"UPDATE_TIME" DATE, 
	"ENABLED" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 
