
  CREATE TABLE "SAJET"."SYS_PART_QC_ITEM" 
   (	"PART_ID" NUMBER NOT NULL ENABLE, 
	"VERSION" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ROUTE_ID" NUMBER NOT NULL ENABLE, 
	"NODE_ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"ITEM_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"ITEM_PHASE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"ITEM_SEQ" NUMBER NOT NULL ENABLE, 
	"INPUT_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"VALUE_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"VALUE_DEFAULT" VARCHAR2(20 BYTE), 
	"VALUE_LIST" VARCHAR2(3000 BYTE), 
	"CONVERT_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"COLUMN_ITEM" VARCHAR2(20 BYTE) DEFAULT '1' NOT NULL ENABLE, 
	"ROW_ITEM" VARCHAR2(20 BYTE) DEFAULT '1' NOT NULL ENABLE, 
	"NECESSARY" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"PRINT" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"UNIT_ID" NUMBER NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE NOT NULL ENABLE, 
	"ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "SYS_PART_QC_ITEMS_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."PART_ID" IS 'SYS_PART.PART_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."VERSION" IS 'SYS_PART.VERSION';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ROUTE_ID" IS 'SYS_RC_ROUTE.ROUTE_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."NODE_ID" IS 'SYS_RC_ROUTE_DETAIL.NODE_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."PROCESS_ID" IS 'SYS_PROCESS.PROCESS_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ITEM_ID" IS '項目 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ITEM_NAME" IS '項目名稱';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ITEM_TYPE" IS '項目類型（0：製程條件/ 1：蒐集項目）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ITEM_PHASE" IS '被參照的階段（I：投入/ O：產出/ A：投入及產出）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ITEM_SEQ" IS '項目顯示順序';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."INPUT_TYPE" IS '輸入方式（K：文字輸入/ S：清單/ R：有範圍的數值輸入）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."VALUE_TYPE" IS '參數類型（V：文字/ N：數字）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."VALUE_DEFAULT" IS '預設值';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."VALUE_LIST" IS '清單項目，或是範圍上下限';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."CONVERT_TYPE" IS '字母大小寫轉換';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."COLUMN_ITEM" IS '項目欄位';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ROW_ITEM" IS '項目列位';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."NECESSARY" IS '項目收集的必要性（Y：必須收集的項目/ N：選擇性收集的項目）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."PRINT" IS '列印輸出項目（Y：要列印的項目/ N：不列印的項目）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."UNIT_ID" IS 'SYS_UNIT.UNIT_ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."UPDATE_USERID" IS '更新資料的人員 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."UPDATE_TIME" IS '更新時間';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_ITEM"."ENABLED" IS '資料啟用狀態';
 

  CREATE INDEX "SAJET"."SPQI_IDX_1" ON "SAJET"."SYS_PART_QC_ITEM" ("PART_ID", "VERSION", "ROUTE_ID", "NODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 
