
  CREATE TABLE "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL" 
   (	"TYPE_ID" NUMBER DEFAULT 0, 
	"REASON_ID" NUMBER, 
	"REASON_CODE" VARCHAR2(25 BYTE), 
	"REASON_DESC" VARCHAR2(100 BYTE), 
	"DESC2" VARCHAR2(100 BYTE), 
	"COUNT_WORKTIME" NUMBER, 
	"ENABLED" VARCHAR2(10 BYTE), 
	"UPDATE_USERID" NUMBER, 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL"."TYPE_ID" IS '停機代碼類型';
 
   COMMENT ON COLUMN "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL"."REASON_ID" IS '系統產生的唯一值';
 
   COMMENT ON COLUMN "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL"."REASON_DESC" IS '維修原因描述';
 
   COMMENT ON COLUMN "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL"."DESC2" IS '維修原因描述2';
 
   COMMENT ON COLUMN "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL"."ENABLED" IS '是否有效';
 
   COMMENT ON TABLE "SAJET"."SYS_HT_MACHINE_DOWN_DETAIL"  IS '機台異常原因表';
 
