
  CREATE TABLE "SAJET"."SYS_HT_PROCESS_OPTION" 
   (	"FACTORY_ID" NUMBER, 
	"STAGE_ID" NUMBER, 
	"PROCESS_ID" NUMBER, 
	"OPTION1" VARCHAR2(5 BYTE), 
	"OPTION2" VARCHAR2(5 BYTE), 
	"OPTION3" VARCHAR2(5 BYTE), 
	"OPTION4" VARCHAR2(5 BYTE), 
	"OPTION5" VARCHAR2(5 BYTE), 
	"OPTION6" VARCHAR2(5 BYTE), 
	"OPTION7" VARCHAR2(5 BYTE), 
	"OPTION8" VARCHAR2(5 BYTE), 
	"OPTION9" VARCHAR2(5 BYTE), 
	"OPTION10" VARCHAR2(5 BYTE), 
	"UPDATE_USERID" NUMBER, 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 
