ALTER TABLE SAJET.SYS_PROCESS_OPTION MODIFY
    OPTION8 DEFAULT '0';

UPDATE SAJET.SYS_PROCESS_OPTION
SET
    OPTION8 = '0';

COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION"."OPTION8" IS
    '標準工時（分鐘）';