
  CREATE TABLE "SAJET"."SYS_PROCESS_OPTION_PART" 
   (	"PART_ID" NUMBER, 
	"ROUTE_ID" NUMBER, 
	"NODE_ID" NUMBER, 
	"PROCESS_ID" NUMBER, 
	"OPTION1" NUMBER DEFAULT 0, 
	"OPTION2" VARCHAR2(20 BYTE), 
	"OPTION3" VARCHAR2(20 BYTE), 
	"OPTION4" VARCHAR2(20 BYTE), 
	"OPTION5" VARCHAR2(20 BYTE), 
	"OPTION6" VARCHAR2(20 BYTE), 
	"OPTION7" VARCHAR2(20 BYTE), 
	"OPTION8" VARCHAR2(20 BYTE), 
	"OPTION9" VARCHAR2(20 BYTE), 
	"OPTION10" VARCHAR2(20 BYTE), 
	"UPDATE_USERID" NUMBER, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."PART_ID" IS '物料 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."ROUTE_ID" IS '生產途程 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."NODE_ID" IS '生產途程節點 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."PROCESS_ID" IS '製程 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."OPTION1" IS '標準工時（分鐘）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."UPDATE_USERID" IS '更新資料的人員 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PROCESS_OPTION_PART"."UPDATE_TIME" IS '更新資料的時間';
 
   COMMENT ON TABLE "SAJET"."SYS_PROCESS_OPTION_PART"  IS '物料製程特殊設定';
 
