
  CREATE TABLE "SAJET"."SYS_PART_QC_OPTION" 
   (	"PART_ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"NODE_ID" NUMBER, 
	"OPTION1" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION2" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION3" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION4" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION5" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION6" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION7" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION8" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION9" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"OPTION10" VARCHAR2(5 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."PART_ID" IS '料號 ID（SAJET.SYS_PART.PART_ID）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."PROCESS_ID" IS '製程 ID（SAJET.SYS_PROCESS.PROCESS_ID）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."NODE_ID" IS '生產途程節點 ID（SAJET.SYS_RC_ROUTE_DETAIL.NODE_ID）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."OPTION1" IS '是否首件檢（Y：是/ N：否）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."OPTION2" IS '是否末件檢（Y：是/ N：否）';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."UPDATE_USERID" IS '更新資料的人員 ID';
 
   COMMENT ON COLUMN "SAJET"."SYS_PART_QC_OPTION"."UPDATE_TIME" IS '更新資料時間';
 
