
  CREATE TABLE "SAJET"."G_RC_C025" 
   (	"WORK_ORDER" VARCHAR2(25 BYTE), 
	"RC_NO" VARCHAR2(50 BYTE), 
	"PART_ID" NUMBER, 
	"VERSION" VARCHAR2(25 BYTE), 
	"ROUTE_ID" NUMBER DEFAULT 0, 
	"FACTORY_ID" NUMBER DEFAULT 0, 
	"PDLINE_ID" NUMBER DEFAULT 0, 
	"STAGE_ID" NUMBER DEFAULT 0, 
	"NODE_ID" NUMBER DEFAULT 0, 
	"PROCESS_ID" NUMBER DEFAULT 0, 
	"SHEET_NAME" VARCHAR2(40 BYTE) DEFAULT 0, 
	"TERMINAL_ID" NUMBER DEFAULT 0, 
	"TRAVEL_ID" NUMBER DEFAULT 1, 
	"NEXT_NODE" NUMBER DEFAULT 0, 
	"NEXT_PROCESS" NUMBER DEFAULT 0, 
	"CURRENT_STATUS" NUMBER DEFAULT 0, 
	"CURRENT_QTY" NUMBER DEFAULT 0, 
	"IN_PROCESS_EMPID" NUMBER, 
	"IN_PROCESS_TIME" DATE, 
	"WIP_IN_QTY" NUMBER DEFAULT NULL, 
	"WIP_IN_EMPID" NUMBER, 
	"WIP_IN_MEMO" VARCHAR2(250 BYTE), 
	"WIP_IN_TIME" DATE, 
	"WIP_OUT_GOOD_QTY" NUMBER DEFAULT NULL, 
	"WIP_OUT_SCRAP_QTY" NUMBER DEFAULT NULL, 
	"WIP_OUT_EMPID" NUMBER, 
	"WIP_OUT_MEMO" VARCHAR2(250 BYTE), 
	"WIP_OUT_TIME" DATE, 
	"OUT_PROCESS_EMPID" NUMBER, 
	"OUT_PROCESS_TIME" DATE, 
	"HAVE_SN" NUMBER DEFAULT 0, 
	"PRIORITY_LEVEL" NUMBER DEFAULT 0, 
	"UPDATE_USERID" NUMBER, 
	"UPDATE_TIME" DATE, 
	"CREATE_TIME" DATE, 
	"BATCH_ID" NUMBER, 
	"EMP_ID" NUMBER DEFAULT 0, 
	"WIP_PROCESS" NUMBER DEFAULT 0, 
	"QC_RESULT" VARCHAR2(10 BYTE), 
	"QC_NO" VARCHAR2(50 BYTE), 
	"BONUS_QTY" NUMBER DEFAULT 0, 
	"WORKTIME" NUMBER DEFAULT 0, 
	"INITIAL_QTY" NUMBER DEFAULT 0, 
	"RELEASE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"WORKHOUR" NUMBER DEFAULT 0, 
	"RC_TOOL_NO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 33554432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSRT" ;


   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WORK_ORDER" IS '工單號碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."RC_NO" IS '流程卡號碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."PART_ID" IS '料號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."VERSION" IS '版本號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."ROUTE_ID" IS '途程編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."FACTORY_ID" IS '廠別編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."PDLINE_ID" IS '生產線編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."STAGE_ID" IS '區段編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."NODE_ID" IS '節點編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."PROCESS_ID" IS '製程編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."SHEET_NAME" IS '製程表單編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."TERMINAL_ID" IS '工作站編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."TRAVEL_ID" IS '歷程編號(流水號遞增)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."NEXT_NODE" IS '下站節點編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."NEXT_PROCESS" IS '下站製程編號';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."CURRENT_STATUS" IS '流程卡目前狀態(0:Queue,1:Running,2:Hold,6:Split,7:Merge,8:Scrap,9:Finish,10:Inv,11:Wait Transfer,12:Transfer)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."CURRENT_QTY" IS '目前數量';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."IN_PROCESS_EMPID" IS '進入製程的員工代碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."IN_PROCESS_TIME" IS '進入製程的時間';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_IN_QTY" IS 'INPUT數量';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_IN_EMPID" IS 'INPUT員工代碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_IN_MEMO" IS 'INPUT說明';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_IN_TIME" IS 'INPUT時間';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_OUT_GOOD_QTY" IS 'OUTPUT良品數';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_OUT_SCRAP_QTY" IS 'OUTPUT報廢數';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_OUT_EMPID" IS 'OUTPUT員工代碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_OUT_MEMO" IS 'OUTPUT說明';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WIP_OUT_TIME" IS 'OUTPUT時間';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."OUT_PROCESS_EMPID" IS '離開製程的員工代碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."OUT_PROCESS_TIME" IS '離開製程的時間';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."HAVE_SN" IS '序號管理(0:否,1:是)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."PRIORITY_LEVEL" IS '優先等級(0:正常,1:優先,2:緊急)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."UPDATE_USERID" IS '資料異動人員';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."UPDATE_TIME" IS '資料異動時間';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."CREATE_TIME" IS '建立時間';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."BATCH_ID" IS '批次號碼';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."EMP_ID" IS '展標籤執行員工';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."BONUS_QTY" IS '紀錄流程卡當站WIP OUT BONUS數量';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WORKTIME" IS '累計當站WIP OUT BONUS數量(分)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."INITIAL_QTY" IS '紀錄流程卡最初展開的數量(包含拆批後的子批)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."RELEASE" IS '初次展開(Y:是,N:否)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."WORKHOUR" IS '紀錄當站在WIP OUT手輸工時(分)';

   COMMENT ON COLUMN "SAJET"."G_RC_C025"."RC_TOOL_NO" IS 'RC對應鐵牌號';

   COMMENT ON TABLE "SAJET"."G_RC_C025"  IS '流程卡歷程紀錄表';


  CREATE INDEX "SAJET"."G_RC_C025_PROCESS" ON "SAJET"."G_RC_C025" ("PROCESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 917504 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;


  CREATE INDEX "SAJET"."G_RC_C025_RC" ON "SAJET"."G_RC_C025" ("RC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;


  CREATE INDEX "SAJET"."G_RC_C025_WO" ON "SAJET"."G_RC_C025" ("WORK_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;

