--------------------------------------------------------
--  已建立檔案 - 星期四-七月-08-2021   
--------------------------------------------------------
REM INSERTING into SAJET.SYS_PROGRAM_FUN_NAME
SET DEFINE OFF;
Insert into SAJET.SYS_PROGRAM_FUN_NAME (PROGRAM,FUNCTION,DLL_FILENAME,FUN_PARAM,FUN_TW,SHOW_FLAG,FUN_TYPE,FUN_TYPE_TW,ENABLED,WEB_FLAG,FORM_NAME,FUN_ENG,FUN_TYPE_ENG,FUN_DESC_ENG,FUN_DESC_TW,FUN_IDX,FUN_TYPE_IDX,FUN_DESC_CN,FUN_TYPE_CN,FUN_CN,FUN_TYPE_TH,FUN_TH,FUN_DESC_TH) values ('WIP','RCInput_C025','RCInput_C025.dll',null,'流程卡投入 C025','0','C025 Execution','C025 執行','Y','N','fMain','RCInput_C025','C025 Execution','RCInput_C025','流程卡投入 C025',0,2,null,null,null,null,null,null);

Insert into SAJET.SYS_PROGRAM_FUN_AUTHORITY (PROGRAM,FUNCTION,AUTH_SEQ,AUTHORITYS) values ('WIP','RCInput_C025',0,'Read Only');
Insert into SAJET.SYS_PROGRAM_FUN_AUTHORITY (PROGRAM,FUNCTION,AUTH_SEQ,AUTHORITYS) values ('WIP','RCInput_C025',1,'Allow To Change');
Insert into SAJET.SYS_PROGRAM_FUN_AUTHORITY (PROGRAM,FUNCTION,AUTH_SEQ,AUTHORITYS) values ('WIP','RCInput_C025',2,'Full Control');
Insert into SAJET.SYS_PROGRAM_FUN_AUTHORITY (PROGRAM,FUNCTION,AUTH_SEQ,AUTHORITYS) values ('WIP','RCInput_C025',3,'Allow To Execute');
