CREATE OR REPLACE PROCEDURE SJ_RC_QC_CLEAR_TEMP(I_QCLOT IN VARCHAR2,
                                                O_RES   OUT VARCHAR2) IS

BEGIN
  O_RES := 'OK';
  
  DELETE FROM SAJET.G_QC_SN_TESTITEM_TEMP WHERE QC_LOTNO = I_QCLOT;

  DELETE FROM SAJET.G_QC_SN_DEFECT_TEMP WHERE QC_LOTNO = I_QCLOT;

EXCEPTION
  WHEN OTHERS THEN
    O_RES := 'SJ_RC_QC_CLEAR_TEMP ERROR' || CHR(10) || CHR(13) || SQLERRM;
    ROLLBACK;
END;
/
