UPDATE SAJET.SYS_BASE_PARAM
SET
    PARAM_VALUE = ' WITH RC_LIST AS ( SELECT A.WORK_ORDER, A.RC_NO, A.PART_ID, A.VERSION, A.ROUTE_ID, A.PROCESS_ID, A.FACTORY_ID, A.CURRENT_QTY FROM SAJET.G_RC_TRAVEL A, SAJET.SYS_PROCESS B WHERE A.RC_NO = :SN AND B.OPERATE_ID = 5 AND B.ENABLED = ''Y'' AND A.PROCESS_ID = B.PROCESS_ID ORDER BY A.UPDATE_TIME DESC ), RC_INFO AS ( SELECT * FROM RC_LIST WHERE ROWNUM = 1 ) SELECT A.RC_NO, A.WORK_ORDER, B.PART_NO, ROUTE_NAME, PROCESS_NAME, FACTORY_CODE, A.VERSION, A.PROCESS_ID, A.PART_ID, CURRENT_QTY QTY, CURRENT_QTY GOOD_QTY, 0 SCRAP_QTY, F.WO_OPTION2, B.SPEC1, B.SPEC2 FROM RC_INFO A, SAJET.SYS_PART B, SAJET.SYS_RC_ROUTE C, SAJET.SYS_PROCESS D, SAJET.SYS_FACTORY E, SAJET.G_WO_BASE F WHERE A.PART_ID = B.PART_ID AND A.ROUTE_ID = C.ROUTE_ID AND A.PROCESS_ID = D.PROCESS_ID AND A.FACTORY_ID = E.FACTORY_ID AND A.WORK_ORDER = F.WORK_ORDER '
WHERE
    PROGRAM = 'WIP'
    AND PARAM_NAME = 'IPQC'
    AND PARAM_TYPE = 'SQL'
    AND DEFAULT_VALUE = 'SQL';
