
  CREATE TABLE "SAJET"."G_QC_VALUE" 
   (	"RC_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"NODE_ID" NUMBER NOT NULL ENABLE, 
	"SN_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_VALUE" VARCHAR2(20 BYTE), 
	"UPDATE_USERID" NUMBER NOT NULL ENABLE, 
	"INSPECTION_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSBS" ;
 

   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."RC_NO" IS '流程卡號（SAJET.G_RC_STATUS.RC_NO）';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."PROCESS_ID" IS '製程 ID（SAJET.SYS_PROCESS_ID）';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."NODE_ID" IS '生產途程節點 ID（SAJET.SYS_RC_ROUTE_DETAIL.NODE_ID）';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."SN_ID" IS '檢驗品的識別碼，由時間戳記產生（YYYY MM DD HH24 MI SS FF）。由此判別哪些抽驗數據為一組';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."ITEM_ID" IS '檢驗項目 ID（SAJET.SYS_PART_QC_ITEM.ITEM_ID）';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."ITEM_VALUE" IS '檢驗結果';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."UPDATE_USERID" IS '更新資料人員的 ID（SAJET.SYS_EMP.EMP_ID）';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."UPDATE_TIME" IS '更新資料的時間';
 
   COMMENT ON COLUMN "SAJET"."G_QC_VALUE"."INSPECTION_TIME" IS '檢驗時間';
 
